// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:bitcoins/core/auth/domain/entities/user.dart';
import 'package:bitcoins/core/onboarding/domain/entities/onboarding.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OnboardingAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OnboardingAdapter());
    registerAdapter(UserAdapter());
  }
}
