import '../../data/models/verify_otp_model.dart';
import '../widgets/widgets.dart';

class MfaOTP extends StatefulWidget {
  const MfaOTP({super.key});

  @override
  State<MfaOTP> createState() => _MfaOTPState();
}

class _MfaOTPState extends State<MfaOTP> {
  final textTheme = Get.textTheme;
  final instance = AuthController.instance;
  final size = MediaQuery.sizeOf(Get.context!);
  final pinController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return FlavorBanner(
      child: Scaffold(
        persistentFooterAlignment: AlignmentDirectional.center,
        persistentFooterButtons: [
          SizedBox(
            width: size.width * 0.85,
            child: ElevatedButton(
              onPressed: () async {
                showDialog(
                  context: context,
                  builder: (context) =>
                      const Center(child: CircularProgressIndicator()),
                );
                final request = VerifyOtpModel(
                  otp: pinController.text,
                  type: 'IN_APP',
                );
                await instance.verifyOtp(request);
              },
              child: Text(
                'verify otp'.toUpperCase(),
                style: textTheme.titleMedium!.copyWith(
                  letterSpacing: 1.5,
                  color: TColors.light,
                ),
              ),
            ),
          ),
        ],
        appBar: AppBar(
          elevation: 0,
          backgroundColor: Colors.transparent,
          leading: const SizedBox.shrink(),
        ),
        body: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
          child: Column(
            children: [
              Text(
                'A code was generated by an authenticator app.',
                textAlign: TextAlign.center,
                style: textTheme.titleMedium,
              ),
              SizedBox(height: size.height * 0.005),
              SizedBox(
                height: size.height * 0.375,
                child: LottieBuilder.network(TImages.lottieImage),
              ),
              SizedBox(height: size.height * 0.008),

              Text(
                'Please enter the code below to verify your account!',
                style: textTheme.titleMedium,
              ),
              SizedBox(height: size.height * 0.025),
              Pinput(
                length: 6,
                controller: pinController,
                pinputAutovalidateMode: PinputAutovalidateMode.onSubmit,
                defaultPinTheme: PinTheme(
                  width: size.height * 0.075,
                  height: size.height * 0.075,
                  textStyle: textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.w800,
                  ),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(
                      width: 1,
                      color: Get.isDarkMode ? TColors.grey : TColors.primary,
                    ),
                  ),
                ),
              ),
              SizedBox(height: size.height * 0.025),
            ],
          ),
        ),
      ),
    );
  }
}
